export const COMPANY = {
  name: 'Boven Frontier International LLP',
  shortName: 'Boven Frontier',
  brand: 'LEXONE · FABIE PLUS · KARE',
  brands: ['LEXONE', 'FABIE PLUS', 'KARE'],
  llpId: 'ACE-5349',
  gstin: '32ABCFB2913N1ZN',
  vision: 'Quality, Reach and Growth',
  tagline: 'Connecting Quality. Creating Markets. Growing Together.',
  address: 'Room No. OP 7/452, Manakkadavu, Kozhikode 673019, India',
  registeredOffice: 'Room No. OP 7/452, Manakkadavu, Kozhikode 673019, India',
  phone1: '+91 96338 90447',
  phone2: '+91 70127 77495',
  whatsappUAE: '+971 50 735 5418',
  whatsappIndia: '+91 96338 90447',
  email1: 'info@bovenfrontier.co.in',
  email2: 'aswin@bovenfrontier.co.in',
  email3: 'shidil@bovenfrontier.co.in',
  website: 'bovenfrontier.co.in',
  operatingHours: 'Mon – Sat: 9:00 AM – 6:30 PM (IST)',
  markets: ['India', 'Middle East', 'GCC'],
  origin: 'Manufactured in India',
}

export const INITIAL_PRODUCTS = [
  {
    id: 'lexone-bathroom-cleaner',
    name: 'Bathroom Cleaner',
    brand: 'LEXONE',
    category: 'SURFACE CARE',
    tagline: 'Powerful limescale and soap scum remover',
    description:
      'Deep penetrating formula cuts through tough water marks, soap scum, and grime on bathroom tiles, sinks, and chrome fittings.',
    variants: ['250 ml', '500 ml'],
    image: '/assets/products/LexoneBathroomcleaner.png',
    scale: 0.85,
    is_featured: true,
    sort_order: 1,
  },
  {
    id: 'lexone-liquid-detergent',
    name: 'Liquid Detergent',
    brand: 'LEXONE',
    category: 'LAUNDRY CARE',
    tagline: 'High-efficiency liquid wash for all fabric types',
    description:
      'Advanced low-suds formulation engineered for front load, top load, and manual bucket wash. Leaves clothes impeccably clean with a fresh lasting aroma.',
    variants: ['1 L', '2 L', '5 L'],
    image: '/assets/products/lexoneliquiddetergent.png',
    scale: 0.85,
    is_featured: false,
    sort_order: 2,
  },
  {
    id: 'lexone-dishwash-liquid',
    name: 'Yellow Dish Wash Liquid',
    brand: 'LEXONE',
    category: 'SURFACE CARE',
    tagline: 'Grease-cutting concentrated dishwashing formula',
    description:
      'Fast-action lime formula removes tough grease, burnt oil stains, and food odours without leaving any white residue on utensils.',
    variants: ['250 ml', '500 ml', '1 L'],
    image: '/assets/products/LexOneDishwash250ml5001lt.png',
    scale: 0.85,
    is_featured: false,
    sort_order: 3,
  },
  {
    id: 'lexone-floor-cleaner',
    name: 'Floor Cleaner',
    brand: 'LEXONE',
    category: 'FLOOR CARE',
    tagline: 'Gleaming surface finish with lasting floral fragrance',
    description:
      'All-surface antibacterial floor cleaner suitable for tiles, marble, granite, and mosaic surfaces. Available in Rose and Lavender fragrances.',
    variants: ['500 ml', '1 L', '5 L'],
    image: '/assets/products/LexoneFloorcleaner500ml.png',
    scale: 0.85,
    is_featured: false,
    sort_order: 4,
  },
]